name = "GeoStats"
uuid = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
author = "JÃºlio Hoffimann <julio.hoffimann@gmail.com>"
version = "0.31.6"

[deps]
DensityRatioEstimation = "ab46fb84-d57c-11e9-2f65-6f72e4a7229f"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GeoClustering = "7472b188-6dde-460e-bd07-96c4bc049f7e"
GeoEstimation = "a4aa24f8-9f24-4d1a-b848-66d123bfa54d"
GeoLearning = "90c4468e-a93e-43b4-8fb5-87d804bc629f"
GeoSimulation = "220efe8a-9139-4e14-a4fa-f683d572f4c5"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
KrigingEstimators = "d293930c-a38c-56c5-8ebb-12008647b47a"
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
PointPatterns = "e61b41b6-3414-4803-863f-2b69057479eb"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
TableTransforms = "0d432bfd-3ee1-4ac1-886a-39f05cc69a3e"
Variography = "04a0146e-e6df-5636-8d7f-62fa9eb0b20c"

[compat]
DensityRatioEstimation = "0.5"
Distances = "0.10"
GeoClustering = "0.2"
GeoEstimation = "0.9"
GeoLearning = "0.1"
GeoSimulation = "0.7"
GeoStatsBase = "0.25"
KrigingEstimators = "0.8"
LossFunctions = "0.7"
Meshes = "0.22"
PointPatterns = "0.4"
Reexport = "1.0"
ScientificTypes = "2.3, 3.0"
TableTransforms = "1.0"
Variography = "0.14"
julia = "1.6"
