name = "GeoStats"
uuid = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
author = "JÃºlio Hoffimann <julio.hoffimann@gmail.com>"
version = "0.10.1"

[deps]
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
KrigingEstimators = "d293930c-a38c-56c5-8ebb-12008647b47a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Variography = "04a0146e-e6df-5636-8d7f-62fa9eb0b20c"

[compat]
GeoStatsBase = "^0.6"
KrigingEstimators = "^0.3"
Reexport = "^0.2"
Variography = "^0.4"
julia = "1"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Random", "Test"]
