[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
GeoStatsDevTools = "19e549d1-356f-5655-9f3d-c1d6136da705"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Documenter = "â‰¥ 0.22.1"
