[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CoDa = "5900dafe-f573-5c72-b367-76665857777b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
GeoStatsImages = "7cd16168-b42c-5e7d-a585-4f59d326662d"
GeoStatsPlots = "cf22561b-6452-4701-9483-6c69015d00e1"
GeoTables = "e502b557-6362-48c1-8219-d30d308dcdb0"
ImageQuilting = "e8712464-036d-575c-85ac-952ae31322ab"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StratiGraphics = "135379e1-83be-5ae7-9e8e-29dade3dc6c7"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TransformsAPI = "756644eb-7399-463e-a86e-97605fb648cd"
TuringPatterns = "fde5428d-3bf0-5ade-b94a-d334303c4d77"

[compat]
Documenter = "0.27"
